### ISSUE TITLE
GxEPD 7.5bwr path is missing - GxGDEW075Z09

### ISSUE THREAD

**Issue by ansash** [ZinggJM/GxEPD#35]
Forks do still have this class.
Is there a reason why it is not included here any more ?

**Comment by ZinggJM** [comment]
**Yes, because I had got an issue!** 
This class was added by a merge request, but I could not test it, as I do not have this display. And now I finally removed it, because it didn't work correctly, it couldn't, because of missing buffer space in RAM of the target systems.
As a sponsor has now offered to send me this display, I will add a new version that will work at least with ESP32.

**This display is supported by the library GxEPD2_32**
