### ISSUE TITLE
Partial Update LUTs for the GDEW042T2

### ISSUE THREAD

**Issue by cwt137** [ZinggJM/GxEPD#39]
A few weeks ago, Good Display uploaded some sample code to do partial updates for the GDEW042T2. It is located [here](http://www.good-display.com/download_detail/downloadsId=601.html). Inside the file `User/Ap_29demo.h` in the zip, there are some LUTs for partial updates. These differ from the ones listed in this project's `GxGDEW042T2/GxGDEW042T2.c` and `GxGDEW042T2_BK/GxGDEW042T2_BK.c` files. Why the difference?

**Comment by ZinggJM** [comment]
I got informed about the new demo code version and downloaded it. I did not compare it in detail, because it looked like the version from Ben Krasnow at first sight. I will compare it later, unless someone tells me the new demo version works better.
What is the motivation behind your question? Why is this an issue?

**Comment by cwt137** [comment]
Just curious. No real issue

**Comment by ZinggJM** [comment]
closed.
